import abc
from typing import List
import random
import os


class BaseQuestionsSet:
    """
    Base class for QuestionSet. Do not use directly !
    """

    def __init__(
        self,
        name,
        dataset_path: str,
        latex_path: str,
        nb_questions: int = 1,
        consigne: str = None,
    ) -> None:
        self.name = name
        self.nb_questions = nb_questions
        self.consigne = consigne
        self.dataset_path = dataset_path

        self.dataset: List[str] = []
        self._load_dataset()
        self.latex_content = None

        self.path_prefix = f"{latex_path}/tmp/{self.name.lower()}/question"

        if not os.path.exists(f"{latex_path}/tmp/{self.name.lower()}"):
            os.makedirs(f"{latex_path}/tmp/{self.name.lower()}")

        if len(self.dataset) == 0:
            raise ValueError(f"Error creating dataset {self.name}:\n Dataset is empty.")

        if len(self.dataset) < self.nb_questions:
            raise ValueError(
                f"Error creating dataset {self.name}:\nCan not generate {self.nb_questions} questions because the dataset size is only {len(self.dataset)}"
            )

        self.header = (
            "%This file is automatically generated. DO NOT EDIT!\n\n"
            + r"\textit{"
            + self.consigne
            + r"}\\"
            + "\n\n"
        )

    def _pick_indexes(self) -> List[int]:
        return random.sample(range(len(self.dataset)), self.nb_questions)

    @abc.abstractmethod
    def _generate_latex_content(self, indexes: List[int]) -> None:
        """
        Pick the question at random and generate the corresponding latex files.
        """
        pass

    def _write_latex_content(self, filename: str) -> None:
        with open(
            f"{filename}",
            mode="w",
            encoding="UTF-8",
        ) as fp:
            fp.write(self.latex_content)

    @abc.abstractmethod
    def _load_dataset(self) -> None:
        """
        Load the given dataset
        """
        pass

    def get_filename(self, indexes: List[int]) -> str:
        return f"{self.path_prefix}_{'_'.join(str(i+1) for i in indexes)}.tex"

    def generate(self) -> None:
        """
        Pick the question at random and generate the corresponding latex files.
        """

        indexes = self._pick_indexes()
        filename = self.get_filename(indexes)
        if not os.path.exists(filename):
            self._generate_latex_content(indexes)
            self._write_latex_content(filename)
        self.current_file = filename
