import abc
from typing import List
import random
import os


class BaseQuestionsSet:
    """
    Base class for QuestionSet. Do not use directly !
    """

    _ROOT_PATH = None

    def __init__(
        self,
        name,
        dataset_path: str,
        nb_questions: int = 1,
        consigne: str = None,
    ) -> None:
        self.name = name
        self.nb_questions = nb_questions
        self.consigne = consigne
        self.dataset_path = (
            self._ROOT_PATH + "/" + dataset_path
            if self._ROOT_PATH
            else f"{os.getcwd()}/{dataset_path}"
        )
        self.dataset: List[str] = []
        self._load_dataset()
        self.latex_content = None

        if len(self.dataset) == 0:
            raise ValueError(f"Error creating dataset {self.name}:\n Dataset is empty.")

        if len(self.dataset) < self.nb_questions:
            raise ValueError(
                f"Error creating dataset {self.name}:\nCan not generate {self.nb_questions} questions because the dataset size is only {len(self.dataset)}"
            )

        self.header = (
            "%This file is automatically generated. DO NOT EDIT!\n\n"
            + r"\textit{"
            + self.consigne
            + r"}\\"
            + "\n\n"
        )

    def _pick_indexes(self) -> List[int]:
        return random.sample(range(len(self.dataset)), self.nb_questions)

    def _write_latex_content(self, latex_path: str) -> None:
        with open(
            f"{latex_path}/tmp/{self.name.lower()}_set.tex",
            mode="w",
            encoding="UTF-8",
        ) as fp:
            fp.write(self.latex_content)

    @abc.abstractmethod
    def _load_dataset(self) -> None:
        """
        Load the given dataset
        """
        pass

    def generate(self, latex_path: str) -> None:
        """
        Pick the question at random and generate the corresponding latex files.
        """
        if self.latex_content == None:
            self._generate_latex_content()

        self._write_latex_content(latex_path)

    @abc.abstractmethod
    def _generate_latex_content(self, latex_path: str) -> None:
        """
        Pick the question at random and generate the corresponding latex files.
        """
        pass
