exam:
  name: Best courses ever
  code: BEAMS666
  year: 1873-2024
  session: 69nd
  reset_page_counter: true

sets:
  - short:
      name: Theory
      path: "short_questions.txt"
      size: 1
      consigne: "Chat GPT is allowed. Preparation time: $\\sim$ 10 sec."
      blank_line: 4
  - large:
      name: Project
      path: "large_questions"
      size: 1
      consigne: "Michel Osée is allowed for this part."
      blank_page: 1
      
