import abc
from typing import List
import random


class BaseQuestionsSet:
    """
    Base class for QuestionSet. Do not use directly !
    """

    def __init__(
        self,
        name,
        dataset_path: str,
        nb_questions: int = 1,
        consigne: str = None,
    ) -> None:
        self.name = name
        self.nb_questions = nb_questions
        self.consigne = consigne
        self.dataset_path = dataset_path
        self.dataset: List[str] = []
        self._load_dataset()
    
        if len(self.dataset) == 0:
            raise ValueError(
                f"Error creating dataset {self.name}:\n Dataset is empty."
            )

        if len(self.dataset) < self.nb_questions:
            raise ValueError(
                f"Error creating dataset {self.name}:\nCan not generate {self.nb_questions} questions because the dataset size is only {len(self.dataset)}"
            )

        self.header = (
            "%This file is automatically generated. DO NOT EDIT!\n\n"
            + r"\textit{"
            + self.consigne
            + r"}\\"
            + "\n\n"
        )
        
    def _pick_indexes(self) -> List[int]:
        return random.sample(range(len(self.dataset)), self.nb_questions)

    @abc.abstractmethod
    def _load_dataset(self) -> None:
        """
        Load the given dataset
        """
        pass

    @abc.abstractmethod
    def generate(self) -> None:
        """
        Pick the question at random and generate the corresponding latex files.
        """
        pass
